### ISSUE TITLE
Unable to package https://api.osf.io/v2/registrations/b6psa/

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/dcs-packaging-osf#8]
The registration [b6psa](https://api.osf.io/v2/registrations/b6psa/) cannot be packaged due to a bug regarding the serialization of empty `extra` fields in the `registered_meta` attribute.  The underlying cause is documented [here](#2) and with CoS [here](https://github.com/CenterForOpenScience/osf.io/issues/6696).

Stacktrace:
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.dataconservancy.cos.osf.client.model.Registration["registered_meta"]->java.util.LinkedHashMap["item29"]->org.dataconservancy.cos.osf.client.model.RegistrationMetadata["extra"])

	at com.github.jasminb.jsonapi.ResourceConverter.readObjectInternal(ResourceConverter.java:224)
	at com.github.jasminb.jsonapi.ResourceConverter.readObject(ResourceConverter.java:184)
	at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:30)
	at com.github.jasminb.jsonapi.retrofit.JSONAPIResponseBodyConverter.convert(JSONAPIResponseBodyConverter.java:14)
	at retrofit.OkHttpCall.parseResponse(OkHttpCall.java:148)
	at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
	at org.dataconservancy.cos.osf.client.model.mapping.v2_2.graphs.NdTestCaseTest.testSimple(NdTestCaseTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.dataconservancy.cos.osf.client.model.Registration["registered_meta"]->java.util.LinkedHashMap["item29"]->org.dataconservancy.cos.osf.client.model.RegistrationMetadata["extra"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:874)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:337)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3760)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2042)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2529)
	at com.github.jasminb.jsonapi.ResourceConverter.readObjectInternal(ResourceConverter.java:304)
	at com.github.jasminb.jsonapi.ResourceConverter.readObjectInternal(ResourceConverter.java:208)
	... 34 more
```

**Comment by emetsger** [comment]
@msuhovec opened this issue based for you!

**Comment by msuhovec** [comment]
Elliot-

I have followed some of the discussion about this on Slack, and I
appreciated the offer for a temporary Fix.
I talked to Don about this yesterday, and we agreed that we can wait for
the "official" fix.

Thanks,

Mark
